### ISSUE TITLE
Upgrade source_maps dependency

### ISSUE THREAD

**Issue by saden1** [eredo/dartson#19]
The source_maps dependency used by dartson is a bit behind. Please upgrade to the latest version.

**Comment by rayk** [comment]
Eric Can I +1 this issue { Dartson depends version 0.9.3} and Polymer is want 0.9.4... I was just going to overide but in SourceMap 0.10.0 actually removed the 0.9.4 deprecated classes, for example span is gone. Making the assumption you probably used this in the transformers... Anyhow really appreciate it if you can take a look, I trying to get mirror stuff out of code as possible... Hence my interest in your lastest version.

**Comment by eredo** [comment]
Working on it.

**Comment by eredo** [comment]
source_map and source_span dependencies have been updated in dartson 0.2.2
